export enum UserNotification{
    welcome,
    recipeLiked,
    recipeRated,
    gotFollowed,
    gotUnfollowed,
    newUserJoined,
    likedPost,
    likedComment,
    commentedPost,
    commentRecipe,
    addToShopList,
    newPostByFollow,
    newRecipeByFollow,
}